# Generated by Django 4.1.7 on 2023-06-20 20:43

from django.db import migrations, models
import django.db.models.deletion
import infrastructure.entities.client.client


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=125, null=True)),
                ('image', models.ImageField(default='client/image/default.png', max_length=255, upload_to=infrastructure.entities.client.client.get_dynamic_image_filename)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni', models.CharField(max_length=11)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('MS1', 'soltero'), ('MS2', 'casado')], max_length=3)),
                ('occupation', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('place_of_birth', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ACCOUNT_SUCURAL', to='entities.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('number', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('A001', 'personal account'), ('A002', 'company account')], default='A001', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ACCOUNT_OWNER', to='entities.client')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
