# Generated by Django 4.1.7 on 2023-06-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_sucursal_client_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='N/A', max_length=125),
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
    ]
