# Generated by Django 4.1.7 on 2023-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_client_address_alter_client_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
