# Generated by Django 4.1.7 on 2023-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_account_number_alter_client_sucursal_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='code',
            field=models.CharField(default='N/A', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
