# Generated by Django 4.1.7 on 2023-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_transfer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='commission',
            field=models.FloatField(default=0.0015, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('S01', 'pending'), ('S02', 'completed'), ('S03', 'canceled')], default='S02', max_length=3),
        ),
    ]
