# Generated by Django 4.1.7 on 2023-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
