# Generated by Django 4.1.7 on 2023-06-23 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
