from decimal import Decimal

MAXIMUM_LENGTH_ACCOUNT_ALLOWED = 11
MINIMUN_DEPOSIT_ALLOWED = Decimal("100.0")
MINIMUN_WITHDRAWAL_ALLOWED = Decimal("100.0")
DIFAULT_BALANCE_ACCOUNT = Decimal("0.0")
MINIMUM_BALANCE_ACCOUNT_LIMIT_ALLOWED = Decimal("100.00")
TRANSFER_COMMISSION_PERCENTAGE = Decimal("0.0015")  # 0.15% / 100
TRANSACTION_DEPOSIT_COMMISSION_PERCENTAGE = Decimal("0")  # 0% / 100
TRANSACTION_WITHDRAWAL_COMMISSION_PERCENTAGE = Decimal("0.01")  # 1% / 100
MINIMUM_TRANSFER_AMOUNT = Decimal("100.00")
DIFAULT_LENGHT_CODE_TRANSFER = 16
